"""add user_model_configs

Revision ID: 101a295ef705
Revises: b6359214107f
Create Date: 2026-03-09 15:56:21.640268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '101a295ef705'
down_revision: Union[str, Sequence[str], None] = 'b6359214107f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('supports_chat', sa.Boolean(), nullable=False),
    sa.Column('supports_stream', sa.Boolean(), nullable=False),
    sa.Column('supports_json', sa.Boolean(), nullable=False),
    sa.Column('supports_embedding', sa.Boolean(), nullable=False),
    sa.Column('last_test_status', sa.String(length=20), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_model_configs_user_id'), 'user_model_configs', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_model_configs_user_id'), table_name='user_model_configs')
    op.drop_table('user_model_configs')
    # ### end Alembic commands ###
