"""add_session_id_to_usage

Revision ID: e1806eccf29f
Revises: 1aa91ab7806f
Create Date: 2026-03-10 23:08:15.353784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1806eccf29f'
down_revision: Union[str, Sequence[str], None] = '1aa91ab7806f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_records', sa.Column('session_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_usage_records_session_id'), 'usage_records', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_session_id'), table_name='usage_records')
    op.drop_column('usage_records', 'session_id')
    # ### end Alembic commands ###
